springdoc:
  packages-to-scan: com.example.trx.apis
  default-consumes-media-type: application/json;charser=UTF-8
  default-produces-media-type: application/json;charser=UTF-8
  api-docs:
    path: /api
  swagger-ui:
    path: /api/swagger-ui.html
    disable-swagger-default-url: true
    display-request-duration: true
    operations-sorter: alpha
spring:
  profiles:
    active: local
---
####### local

tomcat:
  ajp:
    protocol: AJP/1.3
    port: 17099
    enabled: true
spring:
  datasource:
    url: jdbc:sqlite:./festa.sqlite   # 호스트·포트·DB명
    username:                # DB 계정
    password:                          # DB 비밀번호
    driver-class-name: org.sqlite.JDBC
    hikari:                   # (선택) 풀 사이즈 튜닝
      maximum-pool-size: 10   # 동시 커넥션 최대치
      minimum-idle: 2
      idle-timeout: 30000     # ms
      pool-name: HikariCP
  reactor:
    context-propagation: auto
  jpa:
    hibernate:
      ddl-auto: create        # 개발 단계: create | update | none
    open-in-view: false       # API 프로젝트면 권장
    properties:
      hibernate:
        format_sql: false
        show_sql: false
        dialect: org.hibernate.community.dialect.SQLiteDialect

logging:
  level:
    org.hibernate.SQL: off          # 쿼리 로그
    org.hibernate.type.descriptor: trace # 바인딩 값까지 보고 싶을 때
    org.hibernate.orm.jdbc.bind: off

---
####### prod
tomcat:
  ajp:
    protocol: AJP/1.3
    port: 17099
    enabled: true
spring:
  datasource:
    url: "{{ secret.JDBC_URL }}" # 호스트·포트·DB명
    username:                               # DB 계정
    password:                               # DB 비밀번호
    driver-class-name: org.postgresql.Driver
    hikari:                   # (선택) 풀 사이즈 튜닝
      maximum-pool-size: 10   # 동시 커넥션 최대치
      minimum-idle: 2
      idle-timeout: 30000     # ms
      pool-name: HikariCP
  config:
    activate:
      on-profile: prod
  reactor:
    context-propagation: auto
  jpa:
    hibernate:
      ddl-auto: update        # 개발 단계: create | update | none
    open-in-view: false       # API 프로젝트면 권장
    properties:
      hibernate:
        format_sql: false
        show_sql: false
        dialect: org.hibernate.dialect.PostgreSQLDialect
        # naming 전략 (스프링 기본은 camelCasesnake_case)
logging:
  level:
    org.hibernate.SQL: off          # 쿼리 로그
    org.hibernate.type.descriptor: trace # 바인딩 값까지 보고 싶을 때
    org.hibernate.orm.jdbc.bind: off
